
---
- hosts: computadorMeninos
  gather_facts: False
  pre_tasks:
    - name: apt-get update
      raw: apt-get update -qq
      become: yes
    - name: Install python 2.7
      raw: apt-get install -qq python2.7
      become: yes
    - name: Install python-simplejson
      raw: sudo apt-get -y install python-simplejson
      become: yes

  roles:
     - create-users
